### PR TITLE
Update strategy for user info, following Yahoo's Social Directory Web Service API end of life

### LINKED ISSUE #3: Yahoo's Social Directory Web Service API end of life
Hi!

The public Social Directory API is [ending its life on March 2nd, 2020](https://developer.yahoo.com/oauth/social-directory-eol/?guccounter=2). It needs to be replaced by the UserInfo Endpoint, which is OAuth 2.0 protected.

### PR DESCRIPTION
**Pull request by sunny**
Fixes error since Yahoo's Social Directory Web Service API has hit its end of life.

Currently using this in production to allow people to sign-up using Yahoo without raising exceptions:

```rb
gem "omniauth-yahoo_auth",
    git: "https://github.com/sunny/omniauth-yahoo_auth.git",
    branch: "openid-user-info"
```

Closes #3

### CODE REVIEW

**Comment by sunny** [comment]
@karan-pathak Are you still maintaining this project?

**Comment by karan-pathak** [comment]
Dear @sunny,
I checked all the work that you have been doing on this repo while I was not here. Thank you very much for helping out other users in the process :)
Apologies I've been gone for so long from this repository primarily because I was pursuing my masters in computer science and the workload makes me unable to spend any more time elsewhere. As my degree nears an end, I will start to maintain my previous projects and add a few more that will help others.

For an immediate solution, what I can do is merge this pull request. I looked at the code, which seems good. I believe you have already verified it. So for now this will work as the code in theory seem fine. I will also be validating the code by using the gem myself but that will be at a later point. Please let me know if this sounds okay.

And again thank you very much!

**Comment by karan-pathak** [comment]
@sunny One concern, since you removed the get_user_image function which used the image size option, and replaced it with raw_info['picture'], how will the user get a different size image(32,64,128 or 192) which yahoo supports? 
Also it would be helpful if you can also update the readme, what do you say?

**Comment by sunny** [comment]
Hi @karan-pathak, awesome to have you back :)

> I believe you have already verified it.

Yep, it is currently in production at cults3d.com, feel free to try it out!

> since you removed the get_user_image function which used the image size option, and replaced it with raw_info['picture'], how will the user get a different size image(32,64,128 or 192) which yahoo supports?
> Also it would be helpful if you can also update the readme, what do you say?

I’m afraid Yahoo doesn’t support this anymore, as far as I can tell from [the documentation for the user info endpoint](https://developer.yahoo.com/oauth2/guide/get-user-inf/Get-User-Info-API.html). 

I’ve removed the `image_size` option in the README to reflect that.

**Comment by karan-pathak** [comment]
Hi @sunny!

I've merged your pull request and also published the latest version on Rubygems. Please let me know if everything works as you expected. Cheers!

**Pull request merged**
